# -*- coding: utf-8 -*-
"""UAS pns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKDfFPL6vGbdrACVxmUYvcWr9MFwKvaM

#LANGKAH 1 -PERSIAPAN MODEL DAN BASELINE

#### instalasi streamlite
"""

!pip install streamlit -q

"""## Cell 2"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# 1. Menyiapkan data historis sederhana

X_train = np.array([
    [5, 10],
    [10, 20],
    [15, 5],
    [20, 25],
    [25, 15]
])

# Target: Keuntungan (Juta)

y_train = np.array([
    50,
    80,
    110,
    90,
    150
])

# 2. Melatih model (Mesin Replika)

model = LinearRegression().fit(X_train, y_train)

# 3. Menetapkan Skenario Dasar (Baseline)

baseline_input = np.array([[10, 10]])

baseline_pred = model.predict(baseline_input)[0]

print(f"Prediksi Keuntungan Baseline: Rp {baseline_pred:.2f} Juta")

"""# Langkah 2 - MEMBANGUN LOGIKA SIMULATOR"""

def run_simulation(new_iklan, new_diskon):
 # Input baru dari user (Intervensi)
 intervention_input = np.array([[new_iklan, new_diskon]])

 # Prediksi hasil intervensi
 prediction = model.predict(intervention_input)[0]

 # Menghitung Delta (Selisih)-DELTA ANALYSIS
 delta_y = prediction - baseline_pred

 return prediction, delta_y

"""# Langkah 3 Implementasi UI Interaktif (Konsep Streamlit)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import numpy as np
# import pandas as pd
# from sklearn.linear_model import LinearRegression
# 
# # ======================
# # DATA TRAINING
# # ======================
# 
# X_train = np.array([
#     [5,10],
#     [10,20],
#     [15,5],
#     [20,25],
#     [25,15]
# ])
# 
# y_train = np.array([
#     50,
#     80,
#     110,
#     90,
#     150
# ])
# 
# # ======================
# # MODEL
# # ======================
# 
# model = LinearRegression().fit(X_train, y_train)
# 
# # ======================
# # BASELINE
# # ======================
# 
# baseline_input = np.array([[10,10]])
# baseline_pred = model.predict(baseline_input)[0]
# 
# # ======================
# # FUNGSI SIMULASI
# # ======================
# 
# def run_simulation(new_iklan, new_diskon):
# 
#     intervention_input = np.array([[new_iklan, new_diskon]])
# 
#     prediction = model.predict(intervention_input)[0]
# 
#     delta_y = prediction - baseline_pred
# 
#     return prediction, delta_y
# 
# # ======================
# # STREAMLIT UI
# # ======================
# 
# st.set_page_config(
#     page_title="BeautyRich AI Promotion Simulator",
#     page_icon="💎",
#     layout="wide"
# )
# 
# st.markdown("""
# <div style="
# background: linear-gradient(90deg,#E8D5FF,#FDE2F3);
# padding:20px;
# border-radius:15px;
# text-align:center;
# margin-bottom:20px;
# ">
# <h1>💎 BeautyRich AI Promotion Simulator</h1>
# <p>Smart What-If Analysis for Marketing Strategy</p>
# </div>
# """, unsafe_allow_html=True)
# 
# st.write(
#     "Gunakan slider untuk menguji berbagai skenario promosi dan melihat dampaknya terhadap keuntungan."
# )
# 
# # ======================
# # SIDEBAR
# # ======================
# 
# st.sidebar.header("🎯 Variabel Intervensi")
# 
# iklan_slider = st.sidebar.slider(
#     "Anggaran Iklan (Juta)",
#     0,
#     50,
#     10
# )
# 
# diskon_slider = st.sidebar.slider(
#     "Besaran Diskon (%)",
#     0,
#     50,
#     10
# )
# 
# # ======================
# # SIMULASI
# # ======================
# 
# hasil_pred, delta = run_simulation(
#     iklan_slider,
#     diskon_slider
# )
# 
# # ======================
# # HASIL
# # ======================
# 
# col1, col2 = st.columns(2)
# 
# col1.metric(
#     "💰 Prediksi Keuntungan",
#     f"Rp {hasil_pred:.2f} Juta",
#     f"{delta:.2f} Juta"
# )
# 
# col2.metric(
#     "📊 Baseline",
#     f"Rp {baseline_pred:.2f} Juta"
# )
# 
# # ======================
# # GRAFIK
# # ======================
# 
# st.subheader("📈 Perbandingan Skenario")
# 
# data_plot = pd.DataFrame({
#     "Skenario": ["Baseline", "Intervensi"],
#     "Keuntungan": [baseline_pred, hasil_pred]
# })
# 
# st.bar_chart(
#     data=data_plot,
#     x="Skenario",
#     y="Keuntungan"
# )
# 
# # ======================
# # REKOMENDASI
# # ======================
# 
# if delta > 0:
#     st.success(
#         f"✅ Strategi promosi ini diperkirakan meningkatkan keuntungan sebesar Rp {delta:.2f} juta."
#     )
# else:
#     st.error(
#         f"❌ Strategi promosi ini diperkirakan menurunkan keuntungan sebesar Rp {abs(delta):.2f} juta."
#     )
# 
# # ======================
# # FOOTER
# # ======================
# 
# st.markdown("---")
# st.caption("UAS Pemodelan dan Simulasi | BeautyRich AI Simulator")

!pip install pyngrok

from pyngrok import ngrok
ngrok.set_auth_token("3FXlGQVQNz5M4herKh3BOnCOIoY_7PkhtwgBvAekGzqDMa3Nx")

!streamlit run app.py > /content/logs.txt 2>&1 &

!ngrok config add-authtoken 3FXlGQVQNz5M4herKh3BOnCOIoY_7PkhtwgBvAekGzqDMa3Nx

from pyngrok import ngrok

ngrok.kill()

public_url = ngrok.connect(8501)

print(public_url)